services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
      - ./mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  subscriber:
    build:
      context: .
      dockerfile: subscriber.Dockerfile
    container_name: subscriber
    depends_on:
      - mosquitto
      - mongo
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: python subscriber.py

  publisher:
    build:
      context: .
      dockerfile: publisher.Dockerfile
    container_name: publisher
    depends_on:
      - mosquitto
      - mongo
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    command: python subscriber.py

volumes:
  mongo-data:
  mosquitto-data:
  mosquitto-logs: