services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
      - ./mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  python:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: python
    depends_on:
      - mosquitto
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts

volumes:
  mongo-data:
  mosquitto-data:
  mosquitto-logs: